
---
title: <center> <h1>**Resume**</h1> </center>
output:
  html_document
---

<ins> <h3>Education</h3> </ins>

**Columbia University, New York, NY : Sept 2017 - May 2019** 

MPH Epidemiology, Certificate in Public Health Research Methods


**UC Berkeley, Berkeley, CA : Aug 2011 - Dec 2015**

B.A. Public Health, Minor in Environmental Design & Urbanism


<ins> <h3>Work Experience</h3> </ins>

**UCSF, Division of HIV, Infectious Disease, and Global Medicine, San Francisco, CA : May 2018 – Aug 2018**

*Implementation Science Intern | Living HIV Meta-Analysis Project*

- Systematically search databases for published articles and conference abstracts, following standardized protocol
- Data extraction and development of the fields used for meta-analyses, including quantitative and qualitative information
- Developing the standard operating procedure (SOP), updating systematic review protocol, creating tables assessing quality/validity of evidence (risk of bias, GRADE), and drafting sections for a peer-reviewed journal article
- Interpretation of meta-analysis results including forest plots, funnel plots, and heterogeneity of results and evidence

**San Francisco Public Health Department, San Francisco, CA : Mar 2015 – July 2017**

*Research Assistant | Disease Control and Prevention Unit & Chronic Hepatitis Surveillance Program*

- Salmonella case management: Interview patients and provide health education, handle sensitive occupation restrictions/clearance process, and identify potential sources of exposure/outbreak
- Zika: Manage Zika testing flow for cases, Communicate and coordinate with medical providers, laboratory, and patients on testing procedures, criteria, and protocol
- Chronic Hepatitis B & C: Data entry, laboratory test result triage, surveillance data collection

**Hull Research Group, Berkeley, CA : Jun 2015 – Aug 2015**

*Administrative Data Assistant | Eastbay Collaborative for Underserved Children Program*

- Data entry and audit of information from partner school sites, create forms/templates, organize archives, monitor compliance

<ins> <h3>Skills and Courses</h3> </ins>

**Volunteer Health Interpreters Organization Course (Fall 2014 – UC Berkeley)**: Cantonese proficiency in translating to patients in healthcare setting

**Urban Politics: Policies for Sustainable Cities (Fall 2015 – Yonsei University, South Korea)**: Community-Based Learning Course: Evaluating Sustainability in Seoul Research Project: Housing & Energy in Bongwon Area

**Computer Skills**: Microsoft Word, Excel, PowerPoint, STATA, SAS
